import {useTranslations} from "next-intl";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import ScrollReveal from "@/components/ScrollReveal";
import {Link} from "@/i18n/navigation";

type SectionData={id:string;number:string;module:string;title:string;intro:string;posterTitle:string;benefitsEyebrow:string;benefitsTitle:string;benefitsIntro:string;benefits:string[];processEyebrow:string;steps:{title:string;text:string}[];deliverablesEyebrow:string;deliverables:string[];cta:string;kind:"data"|"workers"|"web"};

function VisualServiceSection({service,imageSrc,reverse=false}:{service:SectionData;imageSrc:string;reverse?:boolean}){return <section className={`section unified-service-section ${service.kind}-unified-service`} id={service.id}><div className="wrap"><ScrollReveal className="service-sequence"><div className="unified-service-heading"><div><p className="eyebrow">{service.module}</p><h2>{service.title}</h2></div><p>{service.intro}</p></div><div className={`data-overview-grid${reverse?" is-reversed":""}`}><div className="data-visual-card"><Image src={imageSrc} alt="" fill sizes="(max-width: 1000px) 100vw, 38vw"/><div className="data-visual-shade"/><div className="data-visual-caption"><span>{service.number} / SERVICE</span><h3>{service.posterTitle}</h3></div></div><div className="data-overview-content"><p className="eyebrow process-label">{service.processEyebrow}</p><div className="data-process-grid">{service.steps.map((step,index)=><article key={step.title}><span>0{index+1}</span><h4>{step.title}</h4><p>{step.text}</p></article>)}</div><p className="eyebrow deliverables-label">{service.deliverablesEyebrow}</p><div className="deliverable-tags">{service.deliverables.map(item=><span key={item}>{item}</span>)}</div><Link href="/contact" className="button button-solid brief-cta">{service.cta} <span aria-hidden="true">↗</span></Link></div></div></ScrollReveal></div></section>}

export default function ServicesPage(){
  const page=useTranslations("servicesPage"),data=useTranslations("dataAnalytics"),workers=useTranslations("digitalWorkers"),web=useTranslations("webApps"),home=useTranslations("home");
  const services:SectionData[]=[
    {id:"data-analytics",number:"01",kind:"data",module:data("module"),title:data("title"),intro:data("intro"),posterTitle:home("service1Title"),benefitsEyebrow:data("outcomesEyebrow"),benefitsTitle:data("outcomesTitle"),benefitsIntro:data("outcomesIntro"),benefits:[data("outcome1Text"),data("outcome2Text"),data("outcome3Text"),data("capability2Text")],processEyebrow:data("processEyebrow"),steps:[1,2,3,4].map(n=>({title:data(`step${n}Title`),text:data(`step${n}Text`)})),deliverablesEyebrow:data("capabilitiesEyebrow"),deliverables:data.raw("deliverables") as string[],cta:data("cta")},
    ...([{id:"digital-workers",number:"02",kind:"workers",t:workers},{id:"web-apps",number:"03",kind:"web",t:web}] as const).map(({id,number,kind,t})=>({id,number,kind,module:t("module"),title:t("title"),intro:t("intro"),posterTitle:t("posterTitle"),benefitsEyebrow:t("benefitsEyebrow"),benefitsTitle:t("benefitsTitle"),benefitsIntro:t("benefitsIntro"),benefits:[1,2,3,4].map(n=>t(`benefit${n}`)),processEyebrow:t("processEyebrow"),steps:[1,2,3,4].map(n=>({title:t(`step${n}Title`),text:t(`step${n}Text`)})),deliverablesEyebrow:t("deliverablesEyebrow"),deliverables:t.raw("deliverables") as string[],cta:t("cta")}))
  ];
  return <><Navbar/><main className="services-index-page"><header className="work-hero services-index-hero"><div className="service-hero-grid"/><div className="wrap"><p className="eyebrow">{page("eyebrow")}</p><h1>{page("title")}</h1><p>{page("intro")}</p><nav className="services-jump-nav" aria-label={page("jumpLabel")}>{services.map(service=><a href={`#${service.id}`} key={service.id}><span>{service.number}</span>{service.posterTitle}</a>)}</nav></div></header>{services.map(service=><VisualServiceSection service={service} imageSrc={service.kind==="data"?"/data-clarity.jpg":service.kind==="workers"?"/automation-flow.jpg":"/web-interface.jpg"} reverse={service.kind==="workers"} key={service.id}/>)}<section className="closing service-closing"><p className="eyebrow">{page("closingEyebrow")}</p><h2>{page("closingTitle")}</h2><Link className="button button-dark" href="/contact">{home("cta")} <span aria-hidden="true">↗</span></Link></section></main><footer className="compact-footer"><div className="wrap"><div className="footer-main"><div><Link className="logo" href="/">MIRIT<span>AI</span></Link><p>{home("footerText")}</p></div></div><div className="footer-bottom"><span>© 2026 MIRITAI. {home("rights")}</span><span><a href="https://mirit.org">MIRIT</a> · Research · Culture · Innovation</span></div></div></footer></>;
}
