import type {CSSProperties} from "react";
import type {Metadata} from "next";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import SiteFooter from "@/components/SiteFooter";
import ScrollReveal from "@/components/ScrollReveal";
import {Link} from "@/i18n/navigation";

export const metadata:Metadata={title:"About MiritAI | Practical data, AI & software",description:"Meet MiritAI and Carlos Vera Diago, the analyst and builder behind the independent data, automation, and software studio."};

const tools=[
 {icon:"sql",name:"SQL",detail:"PostgreSQL · SQL Server"},{icon:"python",name:"Python",detail:"pandas · scripting"},
 {icon:"powerbi",name:"Power BI",detail:"DAX · reporting"},{icon:"bigquery",name:"BigQuery",detail:"cloud warehouse"},
 {icon:"fabric",name:"Microsoft Fabric",detail:"analytics · lakehouse"},{icon:"databricks",name:"Databricks",detail:"lakehouse · analytics"},{icon:"dbt",name:"dbt",detail:"models · pipelines"},
 {icon:"sap",name:"SAP",detail:"ERP data"},{icon:"odoo",name:"Odoo",detail:"operations"}
];

function TechIcon({name}:{name:string}) {
 const common="size-7 fill-none stroke-current";
 if(name==="sql") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><ellipse cx="16" cy="7" rx="10" ry="4"/><path d="M6 7v9c0 2.2 4.5 4 10 4s10-1.8 10-4V7M6 16v9c0 2.2 4.5 4 10 4s10-1.8 10-4v-9"/></svg>;
 if(name==="python") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><path d="M16 4c-7 0-7 3-7 7v3h8v2H7c-3 0-5 2-5 6s2 6 5 6h4v-5c0-4 3-7 7-7h5c3 0 5-2 5-5s-2-7-7-7h-5Z"/><path d="M16 28c7 0 7-3 7-7v-3h-8v-2h10c3 0 5-2 5-6s-2-6-5-6h-4v5c0 4-3 7-7 7H9c-3 0-5 2-5 5s2 7 7 7h5Z"/><circle cx="13" cy="8" r="1" className="fill-current stroke-none"/><circle cx="19" cy="24" r="1" className="fill-current stroke-none"/></svg>;
 if(name==="powerbi") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><rect x="4" y="17" width="5" height="10" rx="1"/><rect x="11.5" y="11" width="5" height="16" rx="1"/><rect x="19" y="6" width="5" height="21" rx="1"/><path d="M27 3v24"/></svg>;
 if(name==="bigquery") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><path d="M24.5 23.5 30 29"/><circle cx="15" cy="15" r="11"/><path d="M9 19v-5m5 5V9m5 10v-7"/></svg>;
 if(name==="fabric") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.7"><path d="M8 4h11l5 5v10l-9 9H8l8-8H8Z"/><path d="M19 4 8 15h8l8-8M16 20h8"/></svg>;
 if(name==="databricks") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.7"><path d="m16 3 12 6-12 6L4 9l12-6Z"/><path d="m4 14 12 6 12-6M4 20l12 6 12-6"/><path d="M4 9v3m24-3v3M4 15v3m24-3v3"/></svg>;
 if(name==="dbt") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><circle cx="7" cy="16" r="3"/><circle cx="23" cy="8" r="3"/><circle cx="25" cy="24" r="3"/><path d="m10 15 10-5m-10 8 12 5M16 5v22"/><circle cx="16" cy="5" r="2"/><circle cx="16" cy="27" r="2"/></svg>;
 if(name==="sap") return <svg viewBox="0 0 36 28" className={common} aria-hidden="true"><path d="M2 4h32L24 24H2Z" className="fill-current opacity-15"/><path d="M7 17h4c2 0 2-3 0-3H8c-2 0-2-3 0-3h5m1 6 3-7 3 7m-5-2h4m3 2v-7h4c3 0 3 4 0 4h-4" strokeWidth="1.5"/></svg>;
 return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><circle cx="9" cy="16" r="5"/><circle cx="23" cy="16" r="5"/><path d="M14 16h4M9 11V7m14 4V7"/></svg>;
}

function ToolGrid(){return <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{tools.map((tool,index)=><article key={tool.name} className={`tech-mark group min-h-36 rounded-2xl border border-line bg-canvas/75 p-5 transition-colors hover:border-accent ${index%3===1?"sm:translate-y-4":""}`} style={{"--mark-delay":`${index*-.55}s`} as CSSProperties}><div className="grid size-12 place-items-center rounded-xl border border-accent/30 bg-surface text-accent transition-transform duration-300 group-hover:scale-110"><TechIcon name={tool.icon}/></div><h3 className="mt-6 font-medium">{tool.name}</h3><p className="mt-2 text-xs leading-5 text-muted">{tool.detail}</p></article>)}</div>}

function SocialIcon({name}:{name:"linkedin"|"github"}) {
 if(name==="linkedin") return <svg viewBox="0 0 24 24" aria-hidden="true" className="size-5 fill-current"><path d="M5.2 3.5A2.2 2.2 0 1 1 5.2 8a2.2 2.2 0 0 1 0-4.5ZM3.3 9.5h3.8V21H3.3V9.5Zm6.1 0H13v1.6h.1c.5-.9 1.7-2 3.6-2 3.9 0 4.6 2.5 4.6 5.9v6h-3.8v-5.3c0-1.3 0-3-1.9-3s-2.2 1.4-2.2 2.9V21H9.4V9.5Z"/></svg>;
 return <svg viewBox="0 0 24 24" aria-hidden="true" className="size-5 fill-current"><path d="M12 2a10 10 0 0 0-3.2 19.5c.5.1.7-.2.7-.5v-1.9c-2.8.6-3.4-1.2-3.4-1.2-.5-1.2-1.1-1.5-1.1-1.5-.9-.6.1-.6.1-.6 1 0 1.6 1 1.6 1 .9 1.6 2.4 1.1 2.9.9.1-.7.4-1.1.7-1.4-2.3-.3-4.7-1.1-4.7-5A3.9 3.9 0 0 1 6.7 8.5c-.1-.3-.5-1.3.1-2.8 0 0 .8-.3 2.8 1a9.7 9.7 0 0 1 5 0c2-1.3 2.8-1 2.8-1 .6 1.5.2 2.5.1 2.8a3.9 3.9 0 0 1 1.1 2.8c0 3.9-2.4 4.7-4.7 5 .4.3.7 1 .7 2V21c0 .3.2.6.7.5A10 10 0 0 0 12 2Z"/></svg>;
}

export default function AboutPage(){return <><Navbar/><main id="main-content">
 <header className="px-5 pb-24 pt-28 sm:px-8 lg:px-12 lg:pb-32 lg:pt-36"><ScrollReveal><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">About MiritAI</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[6rem]">Small studio.<br/>Practical systems.</h1><p className="mt-9 max-w-3xl text-lg leading-8 text-muted sm:text-xl">MiritAI is an independent data, AI, and software studio. We help small teams turn scattered information, repetitive work, and awkward processes into clear tools they can depend on.</p></div></ScrollReveal></header>
 <section className="border-y border-line bg-canvas/55 px-5 py-24 sm:px-8 lg:px-12"><ScrollReveal><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">The practice</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Useful before impressive.</h2></div><div className="space-y-6 text-base leading-8 text-muted sm:text-lg"><p>MiritAI starts with the work as it really happens: the spreadsheet passed between teams, the report rebuilt every week, or the useful idea still waiting for a simple interface.</p><p>We shape that friction into a focused first system for reporting, automation, or software. Then we make it understandable enough to use, maintain, and improve. The technology matters, but only when it makes the work clearer.</p></div></div></ScrollReveal></section>
 <section className="px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><ScrollReveal><div className="mx-auto grid max-w-7xl items-start gap-14 lg:grid-cols-[260px_1fr] lg:gap-24"><div className="w-full max-w-[240px] text-center"><div className="about-portrait group relative aspect-[4/5] overflow-hidden rounded-3xl border border-line bg-surface"><Image src="/carlos-vera-diago.png" alt="Carlos Vera, founder of MiritAI" fill sizes="240px" className="object-cover object-center transition duration-700 ease-out group-hover:scale-[1.025]" priority/></div><h2 className="mt-5 text-2xl font-semibold leading-tight tracking-[-.035em]">Carlos Vera</h2><p className="mt-2 text-sm text-muted">Founder and Head of Tech</p></div><div className="lg:pt-4"><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Behind the studio</p><h3 className="mt-5 max-w-2xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Operations first. Data by craft.</h3><div className="mt-8 max-w-2xl space-y-5 text-base leading-8 text-muted"><p>I came up through operations and finance, where data problems are rarely abstract. They show up as time lost, numbers people cannot reconcile, and decisions made without a dependable view of the business.</p><p>That experience led me deeper into analytics engineering, automation, and software. My background in communication and business helps me move between the technical details and the people who need to act on them.</p><p>MiritAI is where I bring those disciplines together: one accountable practice, from the first question to the working system.</p></div><div className="mt-9 flex max-w-2xl flex-wrap justify-center gap-3"><a className="inline-flex items-center gap-3 rounded-full border border-line px-5 py-3 font-mono text-xs transition hover:-translate-y-1 hover:border-accent hover:text-accent" href="https://www.linkedin.com/in/carlosveradiago"><SocialIcon name="linkedin"/>LinkedIn</a><a className="inline-flex items-center gap-3 rounded-full border border-line px-5 py-3 font-mono text-xs transition hover:-translate-y-1 hover:border-accent hover:text-accent" href="https://github.com/cgveradi"><SocialIcon name="github"/>GitHub</a></div></div></div></ScrollReveal></section>
 <section className="border-y border-line bg-canvas/55 px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><ScrollReveal><div className="grid gap-12 lg:grid-cols-[.62fr_1.38fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Experience & toolkit</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Built around real operations.</h2><div className="mt-7 max-w-md space-y-4 text-sm leading-7 text-muted"><p>A decade across healthcare and financial operations shaped the way I work: trace the source, understand the process, and build for the decision.</p><p>An MBA and specialist data training add the business and technical foundations. These are the tools I use to connect both sides.</p></div></div><ToolGrid/></div></ScrollReveal></div></section>
 <section className="px-5 py-24 sm:px-8 lg:px-12"><ScrollReveal><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 rounded-[2rem] bg-foreground p-8 text-canvas sm:p-14 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.18em] opacity-60">Start with the friction</p><h2 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">What should work better in your business?</h2></div><Link href="/contact" className="shrink-0 rounded-full bg-canvas px-6 py-3.5 font-mono text-xs font-semibold text-foreground">Start a conversation <span className="ml-3 text-accent">+</span></Link></div></ScrollReveal></section>
 </main><SiteFooter/></>}
