import type {CSSProperties} from "react";
import type {Metadata} from "next";
import Navbar from "@/components/Navbar";
import SiteFooter from "@/components/SiteFooter";
import ScrollReveal from "@/components/ScrollReveal";
import {Link} from "@/i18n/navigation";

export const metadata:Metadata={title:"Carlos Vera Diago | MIRITAI",description:"The story, experience, and data practice behind MIRITAI."};
const timeline=[
 {year:"2026",title:"Mirit and MiritAI",text:"I co-founded MIRIT as a broader creative practice. MiritAI is my independent agentic data and software studio: the place where I develop, apply, and showcase my work across data, automation, AI agents, and digital products."},
 {year:"2025–26",title:"Data Analytics Bootcamp",text:"Completed in January 2026 to reinforce my modern data stack skills, particularly Python, and build a more specialised analytics foundation beyond the broader business perspective of my MBA."},
 {year:"2023",title:"Data inside operations",text:"Operations Analyst at General Medical Care in Spain. SAP and Odoo into Power BI, KPI dashboards across two provinces, and a real cost allocation catch."},
 {year:"2020",title:"MBA",text:"Master in Business Administration at Universidad de Barcelona and EAE Business School. Business framing for the technical work."},
 {year:"2019",title:"Operations and finance on the floor",text:"Operational and financial analyst roles across healthcare and banking, where the data problems were real rather than theoretical."},
 {year:"2015",title:"Communication and audiovisual",text:"B.A. in Communication and Multimedia at Universidad de La Sabana. The storytelling foundation behind every report I build."}
];
const tools=[
 {icon:"sql",name:"SQL",detail:"PostgreSQL · SQL Server"},{icon:"python",name:"Python",detail:"pandas · scripting"},
 {icon:"powerbi",name:"Power BI",detail:"DAX · reporting"},{icon:"bigquery",name:"BigQuery",detail:"cloud warehouse"},
 {icon:"dbt",name:"dbt",detail:"models · pipelines"},{icon:"sap",name:"SAP",detail:"ERP data"},
 {icon:"odoo",name:"Odoo",detail:"operations"},{icon:"model",name:"Data modelling",detail:"stars · dimensions"}
];

function TechIcon({name}:{name:string}) {
 const common="size-7 fill-none stroke-current";
 if(name==="sql") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><ellipse cx="16" cy="7" rx="10" ry="4"/><path d="M6 7v9c0 2.2 4.5 4 10 4s10-1.8 10-4V7M6 16v9c0 2.2 4.5 4 10 4s10-1.8 10-4v-9"/></svg>;
 if(name==="python") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><path d="M16 4c-7 0-7 3-7 7v3h8v2H7c-3 0-5 2-5 6s2 6 5 6h4v-5c0-4 3-7 7-7h5c3 0 5-2 5-5s-2-7-7-7h-5Z"/><path d="M16 28c7 0 7-3 7-7v-3h-8v-2h10c3 0 5-2 5-6s-2-6-5-6h-4v5c0 4-3 7-7 7H9c-3 0-5 2-5 5s2 7 7 7h5Z"/><circle cx="13" cy="8" r="1" className="fill-current stroke-none"/><circle cx="19" cy="24" r="1" className="fill-current stroke-none"/></svg>;
 if(name==="powerbi") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><rect x="4" y="17" width="5" height="10" rx="1"/><rect x="11.5" y="11" width="5" height="16" rx="1"/><rect x="19" y="6" width="5" height="21" rx="1"/><path d="M27 3v24"/></svg>;
 if(name==="bigquery") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><path d="M24.5 23.5 30 29"/><circle cx="15" cy="15" r="11"/><path d="M9 19v-5m5 5V9m5 10v-7"/></svg>;
 if(name==="dbt") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><circle cx="7" cy="16" r="3"/><circle cx="23" cy="8" r="3"/><circle cx="25" cy="24" r="3"/><path d="m10 15 10-5m-10 8 12 5M16 5v22"/><circle cx="16" cy="5" r="2"/><circle cx="16" cy="27" r="2"/></svg>;
 if(name==="sap") return <svg viewBox="0 0 36 28" className={common} aria-hidden="true"><path d="M2 4h32L24 24H2Z" className="fill-current opacity-15"/><path d="M7 17h4c2 0 2-3 0-3H8c-2 0-2-3 0-3h5m1 6 3-7 3 7m-5-2h4m3 2v-7h4c3 0 3 4 0 4h-4" strokeWidth="1.5"/></svg>;
 if(name==="odoo") return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><circle cx="9" cy="16" r="5"/><circle cx="23" cy="16" r="5"/><path d="M14 16h4M9 11V7m14 4V7"/></svg>;
 return <svg viewBox="0 0 32 32" className={common} aria-hidden="true" strokeWidth="1.8"><rect x="3" y="4" width="9" height="7" rx="1"/><rect x="20" y="4" width="9" height="7" rx="1"/><rect x="11.5" y="21" width="9" height="7" rx="1"/><path d="M7.5 11v5h17v-5M16 16v5"/></svg>;
}

function ToolGrid({compact=false}:{compact?:boolean}) {return <div className={`grid ${compact?"h-full grid-cols-3 gap-2":"grid-cols-2 gap-3 sm:grid-cols-4"}`}>{tools.map((tool,index)=><article key={tool.name} className={`tech-mark group rounded-2xl border border-line bg-canvas/75 transition-colors hover:border-accent ${compact?"grid place-items-center p-2":`min-h-40 p-5 ${index%3===1?"sm:translate-y-4":""}`}`} style={{"--mark-delay":`${index*-.55}s`} as CSSProperties}><div className={`${compact?"":"grid size-12 place-items-center rounded-xl border border-accent/30 bg-surface"} text-accent transition-transform duration-300 group-hover:scale-110`}><TechIcon name={tool.icon}/></div>{!compact&&<><h3 className="mt-7 font-medium">{tool.name}</h3><p className="mt-2 text-xs leading-5 text-muted">{tool.detail}</p></>}</article>)}</div>}

function SocialIcon({name}:{name:"linkedin"|"github"|"miritai"}) {
 if(name==="linkedin") return <svg viewBox="0 0 24 24" aria-hidden="true" className="size-5 fill-current"><path d="M5.2 3.5A2.2 2.2 0 1 1 5.2 8a2.2 2.2 0 0 1 0-4.5ZM3.3 9.5h3.8V21H3.3V9.5Zm6.1 0H13v1.6h.1c.5-.9 1.7-2 3.6-2 3.9 0 4.6 2.5 4.6 5.9v6h-3.8v-5.3c0-1.3 0-3-1.9-3s-2.2 1.4-2.2 2.9V21H9.4V9.5Z"/></svg>;
 if(name==="github") return <svg viewBox="0 0 24 24" aria-hidden="true" className="size-5 fill-current"><path d="M12 2a10 10 0 0 0-3.2 19.5c.5.1.7-.2.7-.5v-1.9c-2.8.6-3.4-1.2-3.4-1.2-.5-1.2-1.1-1.5-1.1-1.5-.9-.6.1-.6.1-.6 1 0 1.6 1 1.6 1 .9 1.6 2.4 1.1 2.9.9.1-.7.4-1.1.7-1.4-2.3-.3-4.7-1.1-4.7-5A3.9 3.9 0 0 1 6.7 8.5c-.1-.3-.5-1.3.1-2.8 0 0 .8-.3 2.8 1a9.7 9.7 0 0 1 5 0c2-1.3 2.8-1 2.8-1 .6 1.5.2 2.5.1 2.8a3.9 3.9 0 0 1 1.1 2.8c0 3.9-2.4 4.7-4.7 5 .4.3.7 1 .7 2V21c0 .3.2.6.7.5A10 10 0 0 0 12 2Z"/></svg>;
 return <svg viewBox="0 0 24 24" aria-hidden="true" className="size-5 fill-none stroke-current" strokeWidth="1.8"><circle cx="12" cy="12" r="8"/><path d="M2.5 13.5c4.6-2.7 8.9-4 13-3.8 3.3.2 5.3 1.2 6 3"/><circle cx="17.7" cy="9.9" r="1.3" className="fill-current stroke-none"/></svg>;
}

export default function AboutPage(){return <><Navbar/><main id="main-content">
 <header className="px-5 pb-24 pt-28 sm:px-8 lg:px-12 lg:pb-32 lg:pt-36"><ScrollReveal><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[280px_1fr]"><div className="relative aspect-[4/5] w-full max-w-[260px] overflow-hidden rounded-3xl border border-line bg-surface/70 p-4"><ToolGrid compact/><span className="absolute bottom-2 right-3 font-mono text-[8px] uppercase tracking-[.18em] text-muted">portrait forthcoming</span></div><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Behind the practice</p><h1 className="mt-6 text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-[5rem]">Carlos Vera Diago</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-muted">Data Analyst and Analytics Engineer. Founder of MiritAI. A decade across healthcare and financial operations, an MBA, and a data analytics bootcamp.</p><p className="mt-6 inline-flex rounded-full border border-orange-500/40 px-4 py-2 font-mono text-[10px] uppercase tracking-[.12em] text-muted">Open to remote roles and selective freelance · CEST · ES / EN</p></div></div></ScrollReveal></header>
 <section className="border-y border-line bg-canvas/55 px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><ScrollReveal><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">The path</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Operations first. Data by craft.</h2><div className="mt-8 space-y-5 text-base leading-7 text-muted"><p>I came up through operations and finance, pulling data apart to understand the business, then learned to do it properly. I care about the decision the data is meant to drive, not just the dashboard.</p><p>Communication training and an MBA help me translate between engineers, executives, and clients. The stack is the vehicle. The story is the point.</p></div></div><ol className="rounded-3xl border border-line bg-surface/45 p-7 sm:p-9">{timeline.map(item=><li key={item.year} className="grid gap-3 border-b border-line py-6 first:pt-0 last:border-0 last:pb-0 sm:grid-cols-[70px_1fr]"><span className="font-mono text-xs text-orange-600 dark:text-orange-300">{item.year}</span><div><h3 className="font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{item.text}</p></div></li>)}</ol></div></ScrollReveal></div></section>
 <section className="px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><ScrollReveal><div className="grid gap-12 lg:grid-cols-[.62fr_1.38fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">What I work with</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">A practical data toolkit.</h2><p className="mt-6 max-w-md text-sm leading-6 text-muted">A connected set of tools for turning operational data into systems people can actually use.</p></div><ToolGrid/></div></ScrollReveal></div></section>
 <section className="border-t border-line px-5 py-24 sm:px-8 lg:px-12"><ScrollReveal><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.7fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Connect</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Find the work and the thinking.</h2><div className="mt-9 flex flex-wrap gap-3"><a className="inline-flex items-center gap-3 rounded-full border border-line px-5 py-3 font-mono text-xs transition hover:-translate-y-1 hover:border-accent hover:text-accent" href="https://www.linkedin.com/in/carlosveradiago"><SocialIcon name="linkedin"/>LinkedIn</a><a className="inline-flex items-center gap-3 rounded-full border border-line px-5 py-3 font-mono text-xs transition hover:-translate-y-1 hover:border-accent hover:text-accent" href="https://github.com/cgveradi"><SocialIcon name="github"/>GitHub</a><a className="inline-flex items-center gap-3 rounded-full border border-line px-5 py-3 font-mono text-xs transition hover:-translate-y-1 hover:border-accent hover:text-accent" href="https://miritai.com"><SocialIcon name="miritai"/>MiritAI</a></div></div><div className="self-end text-sm leading-7 text-muted"><strong className="text-foreground">MiritAI is my independent practice.</strong> I am the founder and sole operator. No hidden team, just real work I can explain and demonstrate.</div></div></ScrollReveal></section>
 <section className="px-5 pb-24 sm:px-8 lg:px-12"><ScrollReveal><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 rounded-[2rem] bg-foreground p-8 text-canvas sm:p-14 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.18em] opacity-60">See the proof</p><h2 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Which project should we look at first?</h2></div><Link href="/cases" className="shrink-0 rounded-full bg-canvas px-6 py-3.5 font-mono text-xs font-semibold text-foreground">View case files <span className="ml-3 text-accent">+</span></Link></div></ScrollReveal></section>
 </main><SiteFooter/></>}
