import type {Metadata} from "next";
import Navbar from "@/components/Navbar";
import SiteFooter from "@/components/SiteFooter";
import ScrollReveal from "@/components/ScrollReveal";
import {Link} from "@/i18n/navigation";

export const metadata:Metadata={title:"Cases | MIRITAI",description:"Real data and analytics projects by Carlos Vera Diago."};
type Case={title:string;badge:string;brief:string;approach:string;stack:string;result:string;repo?:string};
const groups:{title:string;note:string;tone:"accent"|"orange";icon:string;cases:Case[]}[]=[
 {title:"Healthcare and clinical operations",note:"SAP · Power BI · Python · BigQuery · multiple medical centres, ES",tone:"accent",icon:"+",cases:[
  {title:"Operations KPI dashboards",badge:"General Medical Care",brief:"Leadership could not see productivity across two provinces. Reporting was manual and slow.",approach:"Consolidated SAP and Odoo operational data into SQL Server and Power BI, then built KPI views leadership actually used.",stack:"SAP · Odoo · SQL Server · Power BI · DAX",result:"Around 30% less reporting time and bottlenecks that had previously been invisible to management."},
  {title:"Hospital readmissions pipeline",badge:"Portfolio · Python",brief:"Analyse readmission patterns to spot risk and inform care planning.",approach:"Prepared and modelled healthcare data in BigQuery, analysed it in Python, and published an interactive Looker Studio layer.",stack:"Python · BigQuery · Looker Studio",result:"A reproducible pipeline and live report that can be reused for other clinical metrics.",repo:"https://github.com/cgveradi"},
  {title:"Cost allocation correction",badge:"General Medical Care",brief:"A centre looked profitable, but the numbers did not add up under scrutiny.",approach:"Traced allocation logic in SAP, found a misassigned cost hiding real losses, and implemented the correction with leadership.",stack:"SAP ERP · Excel · reconciliation",result:"Hidden losses were corrected and future budgeting gained a more reliable cost view."}
 ]},
 {title:"Business, finance and sales",note:"Power BI · Power Query · DAX · SQL · work across Colombia and Spain",tone:"orange",icon:"bars",cases:[
  {title:"Sales analytics star schema",badge:"Portfolio · Power BI",brief:"A small business ran sales on one fragile manual spreadsheet.",approach:"Built a reusable star schema in Power Query with dimensions, transformations, DAX measures, and KPI views.",stack:"Power Query · Power BI · DAX",result:"Decision-ready sales views replaced the manual spreadsheet.",repo:"https://github.com/cgveradi"},
  {title:"Cultural exchange engagement",badge:"MiritAI client",brief:"The client needed to understand who joined and what kept them engaged for the following year’s planning.",approach:"SQL analysis of registration data produced demographic segments and engagement trend reporting.",stack:"SQL · segmentation · reporting",result:"A repeatable evidence base for programme planning and future cohorts."},
  {title:"Physician segmentation",badge:"Portfolio · Python",brief:"Make a messy physician directory usable for analysis.",approach:"Cleaned and explored profiles in pandas, then produced interpretable segments for operational analysis.",stack:"Python · pandas",result:"Clear segments and a practical basis for targeting and operational decisions.",repo:"https://github.com/cgveradi"}
 ]}
];

function CaseCard({item,tone}:{item:Case;tone:"accent"|"orange"}){const accent=tone==="accent"?"text-accent":"text-orange-500 dark:text-orange-300";return <article className={`group relative overflow-hidden rounded-3xl border bg-surface/70 p-7 transition duration-500 ease-out hover:-translate-y-1 sm:p-10 ${tone==="accent"?"border-accent/45 hover:border-accent hover:shadow-[0_20px_70px_-30px_color-mix(in_srgb,var(--accent)_45%,transparent)] before:bg-accent":"border-orange-500/40 hover:border-orange-500 hover:shadow-[0_20px_70px_-30px_rgba(249,115,22,.45)] before:bg-orange-500"} before:absolute before:inset-y-0 before:left-0 before:w-1 before:opacity-70 before:transition-opacity hover:before:opacity-100`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><h3 className="max-w-3xl text-2xl font-medium tracking-[-.03em] sm:text-3xl">{item.title}</h3><span className={`shrink-0 pt-1 font-mono text-[10px] uppercase tracking-[.16em] ${accent}`}>{item.badge}</span></div><div className="mt-10 grid gap-x-14 gap-y-8 lg:grid-cols-2"><div><p className={`font-mono text-[10px] uppercase tracking-[.18em] ${accent}`}>Brief</p><p className="mt-3 text-base leading-7 text-muted">{item.brief}</p></div><div><p className={`font-mono text-[10px] uppercase tracking-[.18em] ${accent}`}>Approach</p><p className="mt-3 text-base leading-7 text-muted">{item.approach}</p></div><div><p className={`font-mono text-[10px] uppercase tracking-[.18em] ${accent}`}>Stack</p><p className={`mt-3 font-mono text-sm leading-7 ${accent}`}>{item.stack}</p>{item.repo&&<a href={item.repo} className="mt-6 inline-flex font-mono text-xs text-muted transition hover:text-foreground"><span className="mr-3 opacity-60">▸</span>repo: <span className="ml-2 text-accent">github.com/cgveradi</span></a>}</div><div><p className={`font-mono text-[10px] uppercase tracking-[.18em] ${accent}`}>Result</p><p className="mt-3 text-base leading-7 text-muted">{item.result}</p></div></div></article>}

function DomainIcon({icon}:{icon:string}){return icon==="bars"?<svg viewBox="0 0 32 32" className="size-8 fill-none stroke-current" strokeWidth="2" strokeLinecap="round"><path d="M5 27V17h5v10M14 27V10h5v17M23 27V4h5v23M3 27h27"/></svg>:<span aria-hidden="true">+</span>}

export default function CasesPage(){return <><Navbar/><main id="main-content"><header className="relative px-5 pb-28 pt-28 sm:px-8 lg:px-12 lg:pb-40 lg:pt-40"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.1fr_.55fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Case files · the work in full</p><h1 className="mt-7 text-6xl font-semibold leading-[.9] tracking-[-.065em] sm:text-8xl lg:text-[7.5rem]">Real projects.<br/>Same standard.</h1></div><aside className="self-end border-l-2 border-violet-500 pl-6 text-sm leading-7 text-muted">The data is sanitised and relabelled for confidentiality, but the problems, methods, and skills come from real operational work.</aside></div></header>{groups.map(group=><section key={group.title} className="border-t border-line px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><ScrollReveal><div className="mb-12 flex flex-col gap-6 sm:flex-row sm:items-center"><span className={`grid size-16 shrink-0 place-items-center rounded-2xl border bg-surface/60 text-3xl font-semibold ${group.tone==="accent"?"border-accent/30 text-accent":"border-orange-500/30 text-orange-500 dark:text-orange-300"}`}><DomainIcon icon={group.icon}/></span><div><h2 className="text-4xl font-normal tracking-[-.04em] sm:text-5xl">{group.title}</h2><p className="mt-3 font-mono text-xs leading-6 tracking-[.05em] text-muted">{group.note}</p></div></div><div className="grid gap-6">{group.cases.map(item=><CaseCard key={item.title} item={item} tone={group.tone}/>)}</div></ScrollReveal></div></section>)}<section className="px-5 pb-24 pt-8 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-8 rounded-[2rem] bg-foreground p-8 text-canvas sm:p-14 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[.18em] opacity-60">A useful case starts with a real constraint</p><h2 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Which problem should we make visible next?</h2></div><Link href="/contact" className="rounded-full bg-canvas px-6 py-3.5 font-mono text-xs font-semibold text-foreground">Start a case <span className="ml-3 text-accent">+</span></Link></div></section></main><SiteFooter/></>}
