import {useTranslations} from "next-intl";
import Navbar from "@/components/Navbar";
import SiteFooter from "@/components/SiteFooter";
import ScrollReveal from "@/components/ScrollReveal";
import BrandWord from "@/components/BrandWord";
import {Link} from "@/i18n/navigation";

const accents=["text-accent","text-violet-400 dark:text-violet-300","text-orange-600 dark:text-orange-300"];

export default function Home(){
  const t=useTranslations("home");
  const practices=[1,2,3].map(n=>({title:t(`service${n}Title`),text:t(`service${n}Text`),problem:t(`service${n}Problem`),outcome:t(`service${n}Outcome`),href:["/services#data-analytics","/services#digital-workers","/services#web-apps"][n-1]}));
  const steps=[1,2,3,4].map(n=>({label:t(`step${n}Label`),title:t(`step${n}Title`),text:t(`step${n}Text`)}));
  return <><Navbar/><main id="main-content">
    <section className="relative flex min-h-[calc(100svh-76px)] items-center overflow-hidden px-5 py-24 text-center sm:px-8 lg:px-12"><div className="hero-entrance mx-auto w-full max-w-7xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">{t("eyebrow")}</p><h1 className="mt-8"><BrandWord hero/></h1><p className="mt-10 text-[clamp(1.5rem,3vw,2.5rem)] font-medium tracking-tight"><span className="text-accent">{t("leadA")}</span> {t("leadB")}</p><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-muted sm:text-lg">{t("intro")}</p><div className="mt-10 flex flex-wrap justify-center gap-3"><Link href="/cases" className="rounded-full bg-foreground px-6 py-3.5 font-mono text-xs font-semibold text-canvas transition hover:-translate-y-1">View selected work <span className="ml-4">+</span></Link><Link href="/about" className="rounded-full border border-line px-6 py-3.5 font-mono text-xs font-semibold transition hover:-translate-y-1 hover:border-accent">About the practice</Link></div><p className="mt-16 font-mono text-[9px] uppercase tracking-[.24em] text-muted">Sailing through useful ideas · orbit 01</p></div></section>
    <section className="border-y border-line bg-canvas/55 px-5 py-24 sm:px-8 lg:px-12" id="practices"><div className="mx-auto max-w-7xl"><ScrollReveal className="reveal-sequence"><div className="grid gap-6 lg:grid-cols-[1fr_.55fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Areas of practice</p><h2 className="mt-5 max-w-4xl text-4xl font-semibold leading-tight tracking-[-.045em] sm:text-6xl">Three ways to make work easier to understand and use.</h2></div><p className="self-end text-base leading-7 text-muted">The practice sits where data, automation, and product design meet. Each project begins with one concrete constraint.</p></div><div className="mt-14 grid overflow-hidden rounded-3xl border border-line lg:grid-cols-3">{practices.map((practice,index)=><Link key={practice.title} href={practice.href} className="group flex min-h-[360px] flex-col border-line p-7 transition hover:bg-surface/80 max-lg:border-b last:max-lg:border-b-0 lg:border-r lg:last:border-r-0"><span className={`font-mono text-xs ${accents[index]}`}>0{index+1}</span><p className="mt-16 text-sm text-muted">{practice.problem}</p><h3 className="mt-3 text-2xl font-semibold tracking-tight">{practice.title}</h3><p className="mt-4 text-sm leading-6 text-muted">{practice.text}</p><div className="mt-auto flex items-end justify-between pt-10"><span className={`text-sm font-medium ${accents[index]}`}>{practice.outcome}</span><span className={`text-xl transition group-hover:-translate-y-1 group-hover:translate-x-1 ${accents[index]}`}>+</span></div></Link>)}</div></ScrollReveal></div></section>
    <section className="px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><ScrollReveal className="reveal-sequence"><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">{t("approachEyebrow")}</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">{t("approachTitle")}</h2><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-4">{steps.map((step,index)=><article key={step.title} className="min-h-72 bg-canvas p-7"><span className="font-mono text-[10px] uppercase tracking-[.16em] text-accent">{step.label}</span><p className="mt-16 font-mono text-xs text-muted">0{index+1}</p><h3 className="mt-4 text-xl font-semibold">{step.title}</h3><p className="mt-3 text-sm leading-6 text-muted">{step.text}</p></article>)}</div></ScrollReveal></div></section>
    <section className="mb-20 px-5 sm:px-8 lg:px-12"><ScrollReveal className="closing-panel mx-auto grid min-h-[360px] max-w-7xl items-center gap-12 overflow-hidden rounded-[2rem] bg-foreground px-7 py-20 text-canvas sm:px-12 lg:grid-cols-[minmax(0,1fr)_auto] lg:px-16"><div><p className="font-mono text-xs uppercase tracking-[.2em] opacity-60">{t("closingEyebrow")}</p><h2 className="mt-6 max-w-4xl text-4xl font-semibold tracking-[-.05em] sm:text-5xl xl:text-6xl">{t("closingTitle")}</h2></div><Link href="/contact" className="inline-flex justify-self-start rounded-full bg-canvas px-6 py-3.5 font-mono text-xs font-semibold text-foreground transition hover:-translate-y-1 lg:justify-self-end">{t("cta")} <span className="ml-4">+</span></Link></ScrollReveal></section>
  </main><SiteFooter/></>;
}
