import { useTranslations } from "next-intl";
import Navbar from "@/components/Navbar";
import { Link } from "@/i18n/navigation";
import ScrollReveal from "@/components/ScrollReveal";

function SystemMap() {
  return <div className="system-map" aria-hidden="true"><div className="map-grid"/><div className="signal-orbit signal-orbit-a"/><div className="signal-orbit signal-orbit-b"/><div className="sputnik"><div className="sputnik-core"><i/><i/><i/></div><span className="antenna antenna-a"/><span className="antenna antenna-b"/><span className="antenna antenna-c"/><span className="antenna antenna-d"/><b>01</b></div><div className="node node-a"><i/><i/><i/><i/><i/><i/></div><div className="node node-b"><i/><i/><i/></div><div className="node node-c"><i/><i/></div><div className="node node-d"><i/><i/><i/><i/><i/><i/></div><div className="wire wire-a"><span/></div><div className="wire wire-b"><span/></div><div className="wire wire-c"><span/></div></div>;
}

function ServiceGlyph({ index }: { index: number }) {
  if (index === 0) return <svg className="service-glyph" viewBox="0 0 180 82" aria-hidden="true"><path className="glyph-grid" d="M10 17H170M10 41H170M10 65H170M42 7V75M90 7V75M138 7V75"/><path className="glyph-signal" d="M10 62L42 54L68 58L90 31L116 39L138 20L170 12"/><circle cx="42" cy="54" r="3"/><circle cx="90" cy="31" r="4"/><circle cx="138" cy="20" r="3"/></svg>;
  if (index === 1) return <svg className="service-glyph" viewBox="0 0 180 82" aria-hidden="true"><ellipse className="glyph-grid" cx="90" cy="41" rx="58" ry="25"/><path className="glyph-grid" d="M90 8V74M23 41H157"/><path className="glyph-signal" d="M90 16C120 16 145 27 145 41S120 66 90 66S35 55 35 41S60 16 90 16M90 30V20M105 49L127 59M75 49L53 59"/><circle className="glyph-core" cx="90" cy="41" r="14"/><path className="glyph-core-lines" d="M84 37H96M84 42H93M84 47H98"/><g className="glyph-task"><rect x="81" y="8" width="18" height="12" rx="3"/><circle cx="86" cy="14" r="1.5"/><path d="M90 14H95"/></g><g className="glyph-task"><rect x="125" y="56" width="18" height="12" rx="3"/><circle cx="130" cy="62" r="1.5"/><path d="M134 62H139"/></g><g className="glyph-task"><rect x="37" y="56" width="18" height="12" rx="3"/><circle cx="42" cy="62" r="1.5"/><path d="M46 62H51"/></g></svg>;
  return <svg className="service-glyph" viewBox="0 0 180 82" aria-hidden="true"><rect className="glyph-frame" x="15" y="10" width="150" height="62" rx="7"/><path className="glyph-grid" d="M15 27H165M68 27V72"/><circle cx="28" cy="19" r="2"/><circle cx="36" cy="19" r="2"/><circle cx="44" cy="19" r="2"/><path className="glyph-signal" d="M28 40H55M28 49H48M80 40H150M80 50H137M80 60H119"/></svg>;
}

export default function Home() {
  const t = useTranslations("home");
  const ticker = t.raw("ticker") as string[];
  const showDevelopmentPages = process.env.NEXT_PUBLIC_SHOW_DEVELOPMENT_PAGES === "true";
  const servicePaths = ["/services#data-analytics","/services#digital-workers","/services#web-apps"];
  const services = [1, 2, 3].map((n) => ({ title: t(`service${n}Title`), text: t(`service${n}Text`), href: showDevelopmentPages ? servicePaths[n-1] : null }));
  const steps = [1, 2, 3, 4].map((n) => ({ label: t(`step${n}Label`), title: t(`step${n}Title`), text: t(`step${n}Text`) }));
  return <><Navbar/><main>
    <header className="hero" id="top"><div className="hero-grid"/><i className="cross cross-a"/><i className="cross cross-b"/><div className="wrap hero-inner"><div className="hero-copy"><p className="eyebrow">{t("eyebrow")}</p><h1>MIRIT<span>AI</span></h1><p className="hero-lead"><b>{t("leadA")}</b> <em>{t("leadB")}</em></p><p className="hero-intro">{t("intro")}</p><div className="hero-actions"><Link href="/contact" className="button button-solid">{t("cta")} <span aria-hidden="true">↗</span></Link><a href="#services" className="button">{t("services")} <span aria-hidden="true">↓</span></a></div></div><div className="hero-visual"><SystemMap/></div></div><div className="ticker hero-ticker" aria-hidden="true"><div className="ticker-track">{[0,1].map(group=><div className="ticker-group" key={group}>{ticker.map((item,index)=><span key={`${group}-${item}-${index}`}>{item} <b>✦</b></span>)}</div>)}</div></div></header>
    <section className="section" id="services"><div className="wrap"><ScrollReveal><div className="section-head"><div><p className="eyebrow">{t("buildEyebrow")}</p><h2>{t("buildTitle")}</h2></div><p>{t("buildIntro")}</p></div><div className="bento">{services.map((service,index)=>{const content=<><span className="card-id">MODULE / 0{index+1}</span><i/><ServiceGlyph index={index}/><div><h3>{service.title}</h3><p>{service.text}</p></div></>;return service.href?<Link className={`service-card service-${index+1} service-card-link`} href={service.href} key={service.title}>{content}<b className="service-card-arrow" aria-hidden="true">↗</b></Link>:<article className={`service-card service-${index+1}`} key={service.title}>{content}</article>;})}</div></ScrollReveal></div></section>
    <section className="section approach" id="approach"><div className="wrap"><ScrollReveal><div className="section-head"><div><p className="eyebrow">{t("approachEyebrow")}</p><h2>{t("approachTitle")}</h2></div><p>{t("approachIntro")}</p></div><div className="steps">{steps.map((step,index)=><article className="step" key={step.label} style={{"--step-index":index} as React.CSSProperties}><span>{step.label}</span><i aria-hidden="true"/><b aria-hidden="true">0{index+1}</b><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></ScrollReveal></div></section>
    <section className="closing"><i className="cross cross-a"/><i className="cross cross-b"/><p className="eyebrow">{t("closingEyebrow")}</p><h2>{t("closingTitle")}</h2><Link className="button button-dark" href="/contact">{t("cta")} <span aria-hidden="true">↗</span></Link></section>
  </main><footer className="compact-footer"><div className="wrap"><div className="footer-main"><div><a className="logo" href="#top">MIRIT<span>AI</span></a><p>{t("footerText")}</p></div></div><div className="footer-bottom"><span>© 2026 MIRITAI. {t("rights")}</span><span><a href="https://mirit.org">MIRIT</a> · Research · Culture · Innovation</span></div></div></footer></>;
}
